"""
Format vocab_raw.json into markdown tables ready to paste into SKILL.md.

Usage:
    python tools/format_vocab.py > tools/vocab_table.md
"""
import json
import sys
from pathlib import Path

# Force UTF-8 output on Windows where default stdout encoding is cp1252
sys.stdout.reconfigure(encoding="utf-8")

ROOT = Path(__file__).resolve().parent
RAW = ROOT / "vocab_raw.json"


def is_lao_only(text: str) -> bool:
    """Check that text contains only Lao Unicode characters (+ ASCII punctuation)."""
    for ch in text:
        cp = ord(ch)
        if cp < 0x80:
            continue
        if 0x0E80 <= cp <= 0x0EFF:
            continue
        return False
    return True


def has_thai_chars(text: str) -> bool:
    """True if text contains any Thai script characters."""
    return any(0x0E00 <= ord(ch) <= 0x0E7F for ch in text)


def emit_table(category: str, records: list[dict]) -> None:
    print(f"\n### {category.title()} ({len(records)} entries)\n")
    print("| Thai (avoid) | Lao (use) | Note |")
    print("|---|---|---|")
    issues = []
    for r in records:
        thai = r["thai"]
        lao = r["lao"]
        note = r.get("note", "").replace("|", "/")
        # Flag suspicious entries
        flag = ""
        if lao == "?" or "uncertain" in note.lower():
            flag = " ⚠️ uncertain"
        elif has_thai_chars(lao):
            flag = " ❌ contains Thai chars"
            issues.append((thai, lao, "thai-chars"))
        elif not is_lao_only(lao):
            flag = " ⚠️ non-Lao chars"
        print(f"| `{thai}` | `{lao}` | {note}{flag} |")
    if issues:
        print(f"\n<!-- Issues to review: {len(issues)} -->", file=sys.stderr)
        for thai, lao, kind in issues:
            print(f"  - {kind}: {thai} -> {lao}", file=sys.stderr)


def main():
    if not RAW.exists():
        print(f"No vocab data at {RAW}", file=sys.stderr)
        sys.exit(1)
    data = json.loads(RAW.read_text(encoding="utf-8"))
    print("<!-- Generated by tools/format_vocab.py — do not edit by hand -->")
    for category, records in data.items():
        emit_table(category, records)


if __name__ == "__main__":
    main()
